[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/demo.rs"
crate-type = ["cdylib"]

[dependencies]
github-flows = "0.1.0"
slack-flows = "0.2.5"
tokio_wasi = { version = "1.25.1", features = ["full"] }
