[package]
name = "github-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio_wasi = { version = "1.25.1", features = ["full"] }
octocrab = { path = "../../octocrab", version = "0.18.1", default-features = false, features = ["wasi"] }
reqwest_wasi = "0.11.14"
once_cell = "1.17.0"
